name: dynamite
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.0
  code_builder: ^4.4.0
  dart_style: ^2.3.1
  json_annotation: ^4.8.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.2
  json_serializable: ^6.6.2
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
