builders:
  dynamite:
    import: 'package:dynamite/builder.dart'
    builder_factories: ['openAPIBuilder']
    build_extensions: { '.openapi.json': ['openapi.dart'] }
    auto_apply: dependents
    build_to: source
    runs_before: ['built_value_generator|built_value']
