include: package:nit_picking/dart.yaml

linter:
  rules:
    prefer_final_parameters: false # Disabled until super.X is no longer complained about in constructors

analyzer:
  exclude:
    - 'lib/src/clients/common'
    - 'lib/src/clients/generated'
