targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: true
      dynamite:
        options:
          pageWidth: 120
          analyzer_ignores:
            - camel_case_types
            - discarded_futures
            - public_member_api_docs
            - unreachable_switch_case
            - camel_case_extensions
          coverage_ignores:
            - 'const .*\._\(\);'
            - 'factory .*\.fromJson\(Map<String, dynamic> json\) => _jsonSerializers\.deserializeWith\(serializer, json\)!;'
            - 'Map<String, dynamic> toJson\(\) => _jsonSerializers\.serializeWith\(serializer, this\)! as Map<String, dynamic>;'
            - 'static BuiltSet<.*> get values => _\$.*Values;'
