targets:
  $default:
    builders:
      json_serializable:
        options:
          # disallow_unrecognized_keys: true # Uncomment this to check that all the models are correct. We can't enable this because the capabilities contain different keys based on which apps are installed
          explicit_to_json: true
