name: nextcloud
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cookie_jar: ^3.0.1
  crypto: ^3.0.2
  crypton: ^2.0.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  version: ^3.0.2
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.2.1
  coverage: ^1.6.1
  dynamite:
    path: ../dynamite
  json_serializable: ^6.3.2
  nextcloud_test:
    path: ../nextcloud_test
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
  test: ^1.16.0
