name: nextcloud
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  intl: ^0.17.0
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  # coverage: ^1.3.2
  crypto: ^3.0.1
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: f29382f
  process_run: ^0.12.3+1
  test: ^1.16.0
