name: dynamite_end_to_end_test
publish_to: none
description: Tests for dynamite. Not meant for publishing.
version: 1.0.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  built_value: ^8.6.2
  dynamite_runtime:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite_runtime
dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  built_value_generator: ^8.6.2
  dynamite:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.8
