name: dynamite_end_to_end_test
publish_to: none
description: Tests for dynamite. Not meant for publishing.
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.0.0
  dynamite_runtime:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite_runtime
  meta: ^1.0.0
  universal_io: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  built_value_generator: ^8.7.0
  dynamite:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.9
