name: nextcloud-neon
repository: https://github.com/provokateurin/nextcloud-neon

sdkPath: .fvm/flutter_sdk

bootstrap:
  # It seems so that running "pub get" in parallel has some issues (like
  # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
  # makes the CI much more stable.
  runPubGetInParallel: false

packages:
  - packages/*
  - packages/dynamite/*
  - packages/neon/*

ide:
  intellij:
    enabled: false
