name: nextcloud-neon
repository: https://github.com/provokateurin/nextcloud-neon

sdkPath: .fvm/flutter_sdk

bootstrap:
  # It seems so that running "pub get" in parallel has some issues (like
  # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
  # makes the CI much more stable.
  runPubGetInParallel: false

packages:
  - packages/*
  - packages/dynamite/*
  - packages/neon/*

ide:
  intellij:
    enabled: false

scripts:
  format-check: dart format --output=none --set-exit-if-changed --line-length 120 .
  analyze: dart analyze --fatal-infos .
  test: melos exec --concurrency=1 --fail-fast --dir-exists=test -- "flutter test --concurrency=$(nproc --all)"
