name: neon_news
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.13.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  go_router: ^11.1.2
  html: ^0.15.4
  intl: ^0.18.1
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  wakelock_plus: ^1.1.1
  webview_flutter: ^4.2.4

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.3
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
