name: nextcloud_test
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  nextcloud:
    path: ../nextcloud
  process_run: ^0.12.3+1
  test: ^1.16.0

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
