include: package:neon_lints/flutter.yaml

linter:
  rules:
    # should be enabled for release. https://github.com/nextcloud/neon/issues/692
    public_member_api_docs: false

analyzer:
  exclude:
    - lib/l10n/**
