name: settings
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.9'

dependencies:
  flutter:
    sdk: flutter
  intersperse: ^2.0.0
  rxdart: ^0.27.3

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
