name: dynamite_petstore_example
description: An example showing how to use dynamite for the Petstore example API.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.1
  dynamite_runtime:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite_runtime
  uri: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.7
  built_value_generator: ^8.8.1
  dynamite:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite
