name: app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  neon_files:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_files
  neon_news:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_news
  neon_notes:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_notes
  neon_notifications:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  shared_preferences: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
