name: neon_notes
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  built_collection: ^5.1.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  go_router: ^9.0.3
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon
  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud
  provider: ^6.0.5
  queue: ^3.1.0+2
  rxdart: ^0.27.7
  url_launcher: ^6.1.11
  wakelock_plus: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.4
  go_router_builder: ^2.2.1
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

flutter:
  uses-material-design: true
  assets:
    - assets/
