name: neon_notes
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.1'

dependencies:
  built_collection: ^5.1.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17+1
  go_router: ^10.0.0
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  provider: ^6.0.5
  queue: ^3.1.0+2
  rxdart: ^0.27.7
  url_launcher: ^6.1.12
  wakelock_plus: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints

flutter:
  uses-material-design: true
  assets:
    - assets/
