name: neon_notes
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  built_collection: ^5.1.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon
  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud
  provider: ^6.0.5
  queue: ^3.1.0+2
  rxdart: ^0.27.7
  settings:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/settings
  sort_box:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/sort_box
  url_launcher: ^6.1.11
  wakelock: ^0.6.2

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

dependency_overrides:
  wakelock_windows: # TODO: https://github.com/creativecreatorormaybenot/wakelock/pull/195
    git:
      url: https://github.com/creativecreatorormaybenot/wakelock
      path: wakelock_windows
      ref: 094b4a74c31e547c11525bcc050dbd06b02a1f67

flutter:
  uses-material-design: true
  assets:
    - assets/
