name: neon_notes
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  built_collection: ^5.0.0
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.0
  flutter_material_design_icons: ^1.0.0
  go_router: ^12.0.0
  intl: ^0.18.0
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  nextcloud:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/nextcloud
  queue: ^3.0.0
  rxdart: ^0.27.0
  url_launcher: ^6.0.0
  wakelock_plus: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.3
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/
