name: nextcloud_push_proxy
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 9f625eb
