name: file_icons
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.9'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.1

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 9f625eb

flutter:
  fonts:
    - family: Seti
      fonts:
        - asset: fonts/seti.ttf
