name: dynamite_runtime
description: Helper package for use with dynamite.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  built_value: ^8.5.0

dev_dependencies:
  build_runner: ^2.4.2
  built_collection: ^5.1.1
  built_value_generator: ^8.5.0
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
  test: ^1.24.2
