name: spec_templates
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  path: ^1.8.1
  xml: ^6.1.0
  yaml: ^3.1.0


dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: f29382f

