name: spec_templates
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  path: ^1.8.1
  xml: ^6.1.0

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
