include: package:neon_lints/flutter.yaml

linter:
  rules:
    # should be enabled for release. https://github.com/nextcloud/neon/issues/692
    public_member_api_docs: false
    # TODO: migrate package to new lint rules
    prefer_final_parameters: true
    avoid_final_parameters: false

analyzer:
  exclude:
    - lib/l10n/**
