name: neon_notifications
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  go_router: ^10.1.2
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  provider: ^6.0.5
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
