name: neon_notifications
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.1'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.1
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  provider: ^6.0.5
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints

flutter:
  uses-material-design: true
  assets:
    - assets/
