name: Conventional commits
on:
  pull_request:

jobs:
  conventional-commits:
    name: Conventional commits
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - name: Install dart
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672 # v1
        with:
          sdk: 3.5
      - name: Install commitlint_cli
        run: dart pub get

      - name: Lint conventional commits
        run: dart run commitlint_cli --from=${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to=${{ github.event.pull_request.head.sha }}
