name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  dart-ci:
    name: Dart CI
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache/hosted
          key: dart-ci
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dart
        uses: dart-lang/setup-dart@v1
      - name: Setup
        run: ./tool/setup.sh

      - name: Check formatting
        run: melos run format-check
      - name: Lint code
        run: melos run analyze
      - name: Run tests
        run: melos run test
