name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

concurrency:
  group: dart-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dart-ci:
    name: Dart CI
    runs-on: ubuntu-22.04
    steps:
      - name: Cache dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: ~/.pub-cache/hosted
          key: dart-ci
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install dart
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f # v1
      - name: Setup
        run: ./tool/setup.sh
      - name: Build test Docker image
        run: ./tool/build-dev-container.sh

      - name: Check formatting
        run: melos run format-check
      - name: Lint code
        run: melos run analyze
      - name: Run tests
        run: melos run test
