name: Generate
on:
  pull_request:

concurrency:
  group: generate-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-22.04
    outputs:
      src: ${{ steps.changes.outputs.src}}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - external/**
              - tool/**
              - packages/dynamite/**
              - packages/nextcloud/**

  dart:
    name: Dart
    runs-on: ubuntu-22.04
    needs: changes
    if: needs.changes.outputs.src != 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - name: Submodules
        run: git submodule update --init --depth 0

      - name: Install dart
        uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30 # v1
      - name: Setup
        run: ./tool/setup.sh

      - name: Generate dynamite end to end test
        run: |
          ./tool/generate-dynamite-e2e-test.sh
          if [ -n "$(git status --porcelain)" ]; then
            git --no-pager diff
            exit 1
          fi

      - name: Generate dynamite petstore example
        run: |
          ./tool/generate-dynamite-petstore-example.sh
          if [ -n "$(git status --porcelain)" ]; then
            git --no-pager diff
            exit 1
          fi

      - name: Generate nextcloud
        run: |
          ./tool/generate-nextcloud.sh
          if [ -n "$(git status --porcelain)" ]; then
            git --no-pager diff
            exit 1
          fi

  openapi:
    name: OpenAPI
    runs-on: ubuntu-22.04
    needs: changes
    if: needs.changes.outputs.src != 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - name: Submodules
        run: git submodule update --init --depth 0

      - name: Install php
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Generate specs
        run: |
          ./tool/generate-specs.sh
          if [ -n "$(git status --porcelain)" ]; then
            git --no-pager diff
            exit 1
          fi
