name: Lint
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Find untested Neon APIs
        run: ./tool/find-untested-neon-apis.sh

      - name: Find relative markdown links
        run: ./tool/find-relative-markdown-links.sh
