name: Lint
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Find relative markdown links
        run: ./tool/find-relative-markdown-links.sh
