name: Neon
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: neon-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  untested-apis:
    name: Untested APIs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Find untested Neon APIs
        run: ./tool/find-untested-neon-apis.sh
