name: 'Check spelling'
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: streetsidesoftware/cspell-action@934c74da3775ac844ec89503f666f67efb427fed # v6
        with:
          incremental_files_only: false
