name: 'Check spelling'
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: streetsidesoftware/cspell-action@157048954070986ce4315d0813573a2d8faee361 # v7
        with:
          incremental_files_only: false
