name: 'Update test presets'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0
      - name: Install dart
        uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30 # v1
      - name: Setup
        run: ./tool/setup.sh

      - name: Update presets
        run: ./tool/generate-nextcloud-test-presets.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83 # v6
        with:
          commit-message: "chore(nextcloud_test): Update presets"
          signoff: true
          branch: chore/nextcloud_test/update-presets
          delete-branch: true
          title: "chore(nextcloud_test): Update presets"
          body: ""
